import Head from 'next/head';
import IndexContent from '../components/index-content/IndexContent';

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IndexContent />
    </div>
  );
}
